### ISSUE TITLE
About EET Compatibility

### ISSUE THREAD

**Issue by Amellg** [cmorganbg/Aran-Whitehand#8]
Hello! I see that Aran is "EET recognised" since Beta_Luridel. Does it mean he is supposed to be compatible with EET?
If so, I've tried to installed Aran on EET but failed due to an error:
```
BGII:EE content is being installed.
Compiling 1 dialogue file ...
[aranw/tra/english/c-aranw.tra] has 13732 translation strings
Processing 1 dialogues/scripts ...
[./override/BDORN.DLG] loaded, 12157 bytes
[BDORN.DLG] loaded
[./override/C-ARANB.DLG] loaded, 366558 bytes
[C-ARANB.DLG] loaded
[./override/BDORN25.DLG] loaded, 10824 bytes
[BDORN25.DLG] loaded

ERROR locating resource for 'CHAIN3'
Resource [C-ARN25B.DLG] not found in KEY file:
	[./chitin.key]
ERROR: preprocessing APPEND_EARLY [aranw/dialog/c-aranbg2ee_dorn.d]: Failure("resource [C-ARN25B.DLG] not found for 'CHAIN3'")
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Install Aran Whitehand for SoA and ToB], rolling back to previous state
Unable to Unlink [aranw/backup/0/OTHER.0]: Unix.Unix_error(1, "unlink", "aranw/backup/0/OTHER.0")
[aranw/backup/0/UNSETSTR.0] SET_STRING uninstall info not found
Will uninstall 127 files for [ARANW/SETUP-ARANW.TP2] component 0.
```
Actually I used EET_modConverter to automatically convert the original mod again, finally made it installed sucessfully, and have been playing with Aran for several run-throughs. It works fine overall, except for some issues that may related to chapter references, and some that I'm not sure if they're caused by the mod, EET or the automatic conversion (have no idea if I should report them).

**Comment by cmorganbg** [comment]
C-ARN25B not being installed on EET is probably due to the way I check for ToB - I assume EET has ToB in it since it has BG2EE in it, so I had better go check on what that is about!
Chapter references are definitely an issue with EET - I need to set up the EET related variables.

**Comment by cmorganbg** [comment]
Heh - yep. I have the old filter 

ACTION_IF GAME_IS ~tob bgt bg2ee~ THEN BEGIN

I will fix that to 

ACTION_IF GAME_IS ~tob bgt bg2ee eet~ THEN BEGIN

I will need to search for other instances like that!

**Comment by cmorganbg** [comment]
https://github.com/cmorganbg/Aran-Whitehand/commit/9d4596088f78eb0b97929d82003e3970beff71dd

All fixed on the resources front - I'll put the chapter variables in a new issue.
